[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[font]
size = 18.0

[general]
import = [
	#"~/.config/alacritty/themes/catppuccin/catppuccin-latte.toml"
	"~/.config/alacritty/themes/catppuccin/catppuccin-frappe.toml"
	#"~/.config/alacritty/themes/catppuccin/catppuccin-macchiato.toml"
	#"~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
]
